#  ____    _                       _          _____
# / ___|  (_)  _ __ ___    _ __   | |   ___  |_   _|  _ __     __ _
# \___ \  | | | '_ ` _ \  | '_ \  | |  / _ \   | |   | '_ \   / _` |
#  ___) | | | | | | | | | | |_) | | | |  __/   | |   | |_) | | (_| |
# |____/  |_| |_| |_| |_| | .__/  |_|  \___|   |_|   | .__/   \__,_|
#                         |_|                        |_|

# Place Holders: %time% | %player% | %option%


# !!!!!!!!!!!!!!!!
# This options will support all plugins that use teleport stuff
# If you want the plugin to log the previus teleport locations for the /back command from other plugins -> set this to true
enable-teleport-logging: false
# !!!!!!!!!!!!!!!!

#If you set it to true, you will disable the prefix
#Make sure to restart the server in order to apply it
disable-prefix: false
prefix: "&c[&6SimpleTpa&c]"

#Messages:
# TO DISABLE A MESSAGE - SET IT TO - NONE
# EXAMPLE:
# Console-Isnt-Player: "none"
Console-Isnt-Player: "&6La consola no ha podido usar &cSimpleTpa&6!"
Disabled-World-Message: "&6No puedes usar &cSimpleTpa &6en este mundo!"
Teleport-Message: "&6Te vas a teleportar. No te muevas!. &c%time% &6seconds!"
Teleport-Message-Back-To-Player: "&6Tu &caceptaste&6la solicitud de tp!"
Player-Is-Null: "&6Este jugador no esta &conline&6!"
Player-Doesnt-Have-Back-Point: "&6Este jugador no tiene zonas de muerte!"
Player-Doesnt-Have-Back-Point-1: "&6You don't have any back locations!"
Cooldown-Message: "&6No puedes usar el comando por %time% seconds yet!"
Death-Message: "&6Para volver a tu zona de muerte usa &c/back"
Teleport-Message-Back-To-Sender-TPHEREALL: "&6Enviando solicitud de TP a &ceveryone&6!"
No-Permission-Message: "&6No tienes permiso para usar este comando"
TpaToggle-Deactivated-Player-2: "&c%player% &6deshabilito el &ctpa toggle&6 para ti!"
TpaToggle-Activated-Player-2: "&c%player% &6 ha habilitado el &ctpa toggle&6 para ti!"
TpaToggle-Deactivated-Player: "&6Tu &cdesabilitaste&6 el tpa para &c%player%&6."
TpaToggle-Activated-Player: "&6Tu &chabilitaste&6 el tpa para &c%player%&6."
TpaToggle-Deactivated: "&6Tu &cdesabilitaste&6 la palanca del tpa."
TpaToggle-Activated: "&6Tu &cactivaste&6 la palanca del tpa"
TpaToggled-Player-Message: "&6El jugador tiene &cdisabled &6the teleportation to him!"
Player-Is-Player: "&6No puedes teletransportarte &ca ti mismo&6!"
Already-A-TP-Request: "&6Tu ya &cenviaste &6Una solicitud de TP Si quieres cancelarlo &c/tpcancel player "
Tpa-Usage-Message: "&6Por favor usa: &c/tpa (player)"
Timed-Out-Message: "&6Tu &cteleport&6 ha caducado!"
Sending-Teleport-Request: "&6Enviando solicitud a &c%player%&6. Si quieres cancelarlo: &c/tpcancel player "
Accept-Message: "&6Para aceptar la solicitud de teletransporte, escribe &c/tpaccept"
Deny-Message: "&6Para cancelar la solicitud, escribe &c/tpdeny"
Sent-Request-On-You: "&c%player% &6te ha enviado una solicitud de teletransporte!"
Timed-Out-Here-Message: "&6Su solicitud de teletransporte aquí ha &ccaducado!"
Sending-Teleport-Here-Request: "&6Enviar una solicitud de teletransporte aquí a &c%player%&6. Si quieres cancelarlo usa &c/tpcancel player"
Sent-Here-Request-On-You: "&c%player% &6te ha enviado una solicitud de teletransporte aquí!"
Already-A-TPHere-Request: "&6Ya has &cenviado &6una solicitud de teletransporte aquí! Si quieres cancelarlo usa &c/tpcancel player"
Tpa-Here-Usage-Message: "&6Por favor usa: &c/tpahere (player)"
No-Teleport-Requests: "&6No tienes solicitudes de tpa!"
Invalid-Player: "&6El jugador que quieres tp se salio del servidor!"
Teleport-Message-Back-To-Sender: "&c%player% &6has aceptado la solicitud de tp."
Teleported-Message: "&6Teletransportado!"
Move-Cancel-Message: "&6Te has movido! La solicitud se ha cancelado"
Rejected-Sender: "&6El jugador ha rechazado tu &csolicitud&6!"
Rejected-Message: "&6Rechazaste la &csolicitud&6!"
Player-Is-In-Disabled-World: "&6El jugador al que quieres hacerte tp &cdisabled world&6!"
Tpcancel-Usage-Message: "&6Por favor usa: &c/tpcancel (player)"
Error-Cancelling-Request: "&6No puedes cancelar tu propia &csolicitud!"
Request-Cancelled: "&6Cancelaste exitosamente el &ctpa&6!"
Death-Message-Coords: "&6Tu localización de muerte es: &c%coords%&6!"
Time-Left: "&6Tienes &c%seconds% &6segundos para aceptar o denegar la solicitud"
Damaged-Cancel-Message: "&6Fuiste dañado y la solicitud de teletransporte ha sido eliminada!"
Different-Gamemode: "&6No puedes usar ningún comando de teletransportación, porque estás en modo &cESPECTADOR&6!"

## BUTTONS
#Here you can find the colors https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/ChatColor.html

#Accept Button Properties
Accept-Button: "ACEPTAR"
Accept-Button-Color: "RED"
Accept-Button-Set-Bold: true
Accept-Button-Description: "&6Haz click aquí para &caceptar&6 la solicitud de tpa!"

#Middle Button Properties
Middle-Button: " | "
Middle-Button-Color: "GRAY"
Middle-Button-Set-Bold: true
Middle-Button-Description: "&7 <- Escoger entre -> "

#Deny Button Properties
Deny-Button: "DENEGAR"
Deny-Button-Color: "RED"
Deny-Button-Set-Bold: true
Deny-Button-Description: "&6Haz click aquí para &cdenegar&6 la solicitud de tpa!"

#If you want to disable simpletpa for some worlds, then you can add them by adding - 'NameOfTheWorld'
#Disabled Worlds:
disabled-worlds:
  - 'disabledworld'

# If you set anything to true, you will disable it.
# B A C K    S E T T I N G S

#If you want to disable the back command, then set this to true
disable-back-command: false

# If you want to disable the death coords message, then set this to true
disable-coords-message: false

# If you want to disable saving the death location, then set this to true
disable-back-on-death: false

# If you want to disable saving the TP Locations such as TPA, TPAHERE, then set this to true
disable-back-on-tp: false

#Booleans
#  If you want to disable checking for gamemode if equals to spectator, then set this to true
disable-gamemode-check: false
#  If you want to disable saving the accept or deny buttons, then set this to true
disable-accept-deny-buttons: false
#  If you want to disable saving the particles, then set this to true
disable-particles: false
#  If you want to disable saving the move system, then set this to true
disable-move-system: false

# If you want to disable the invincibility after teleporting, then set this to true
disable-invincibility: false

# Everything works with SECONDS
#Integers
invincibility-seconds: 5
#This will keep the teleport request alive for X seconds
keep-alive: 60
#This will delay the teleportation for X seconds
delay-back-command: 5
delay-teleportation: 5
#Cooldowns
back-cooldown: 10
tpa-cooldown: 10
tpahere-cooldown: 10
tpahereall-cooldown: 10
#To set a custom cooldown, you need to add a permission : simpletpa.cooldown.Y.X where Y is the command and  X are the seconds.
#The options for commands are: tpa | tpahere | back | tpahereall
#Example: simpletpa.cooldown.tpa.300 | simpletpa.cooldown.tpahere.300 | simpletpa.cooldown.tpahereall.300 | simpletpa.cooldown.back.300
#This will set the cooldown for tpa/ tpahere/ tpahereall / back to 300 seconds
